#!/bin/bash

echo "Configuring packages..."
sudo apt-get update -qq && sudo apt-get upgrade -qq
sudo apt-get install -qq perl wget

echo "Downloading TeX Live..."
cd /tmp
wget -q https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -xf install-tl-unx.tar.gz
cd install-tl-*/

echo "Installing TeX Live (unattended)..."
perl install-tl --profile texlive.profile

echo "Installing XeTeX engine..."
sudo apt-get install -qq texlive-xetex

echo "Almost done -- YOU NEED TO UPDATE YOUR PATHS MANUALLY."
echo "  • /usr/local/texlive/2021/texmf-dist/doc/man -> MANPATH"
echo "  • /usr/local/texlive/2021/texmf-dist/doc/info -> INFOPATH"
echo "  • /usr/local/texlive/2021/bin/x86_64-linux -> PATH"
echo "These should be added to your .bashrc/.zshrc/etc. file."
