#!/bin/bash

echo "Configuring packages..."
sudo apt-get update -qq && sudo apt-get upgrade -qq
sudo apt-get install -qq \
    build-essential \
    libbz2-dev \
    libffi-dev \
    libgdbm-dev \
    liblzma-dev \
    libncurses5-dev \
    libnss3-dev \
    libreadline-dev \
    libssl-dev \
    libsqlite3-dev \
    pkg-config \
    wget \
    zlib1g-dev

cd /tmp

for VER do
    FULL=$VER
    if [[ $FULL == *"a"* ]]; then
        PARTIAL="$(cut -d 'a' -f 1 <<< $VER)"
    elif [[ $FULL == *"b"* ]]; then
        PARTIAL="$(cut -d 'b' -f 1 <<< $VER)"
    elif [[ $FULL == *"rc"* ]]; then
        PARTIAL="$(cut -d 'r' -f 1 <<< $VER)"
    else
        echo "Version could be be parsed. Make sure your version follows the PEP 440 format."
        exit 2
    fi

    echo "Downloading Python $FULL..."
    wget -q https://www.python.org/ftp/python/$PARTIAL/Python-$FULL.tgz

    if [[ ! -f Python-$FULL.tgz ]]; then
        echo "That Python version does not exist."
        exit 2
    fi

    tar -xf Python-$FULL.tgz

    echo "Building Python $FULL..."
    cd Python-$FULL
    ./configure -q --enable-optimizations --with-ensurepip=install --with-system-ffi
    make -s -j $(nproc)

    echo "Installing Python $FULL..."
    sudo make -s altinstall
done

echo "All done!"
