#!/bin/bash

echo "Configuring packages..."
sudo apt-get update -qq && sudo apt-get upgrade -qq
sudo apt install -qq perl wget

echo "Downloading TeX Live..."
cd /tmp
wget -q https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -xf install-tl-unx.tar.gz
cd install-tl-*/

echo "Installing TeX Live (unattended)..."
perl install-tl --profile=texlive.profile

echo "Almost done -- YOU NEED TO UPDATE YOUR PATHS MANUALLY. See above."
